CREATE TABLE IF NOT EXISTS Books (
  book_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre (
  genre_id INTEGER PRIMARY KEY AUTOINCREMENT,
  genre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Author (
    author_id INTEGER PRIMARY KEY AUTOINCREMENT,
    author VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BooksGenreMapping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS BooksAuthorMapping (
    id INTEGER PRIMARY KEY,
    book_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL
);